# Generated by Django 3.0.6 on 2020-05-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200315_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
