# Generated by Django 3.0.6 on 2020-05-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200530_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreviewimage',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
